import { Montserrat } from "next/font/google";
import "./globals.css";
import "../../src/styles/premiumbutton.css";
import "../../src/styles/aibutton.css";
import "../../src/styles/custom.css";
import LayoutWrapper from "@/components/LayoutWrapper";
import ContextWrapper from "@/contextProvider/ContextProvider";
import { Toaster } from "react-hot-toast";
import { SessionProviders } from "@/sessionProvider/SessionProvider";

const roboto = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Clerverlyy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className}`}>
        <SessionProviders>
          <Toaster position="bottom-center" />
          <ContextWrapper>
            <LayoutWrapper>{children}</LayoutWrapper>
          </ContextWrapper>
        </SessionProviders>
      </body>
    </html>
  );
}
