import { Montserrat } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "@/components/LayoutWrapper";
import ContextWrapper from "@/contextProvider/ContextProvider";
import { Toaster } from "react-hot-toast";

const roboto = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Clerverlyy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className}`}>
        <Toaster />
        <ContextWrapper>
          <LayoutWrapper>{children}</LayoutWrapper>
        </ContextWrapper>
      </body>
    </html>
  );
}
